version = 1

test_patterns = ["*_test.go"]

# To be conifgured later

# [[analyzers]]
# name = "go" 
# enabled = true

[analyzers.meta]
import_paths = ["github.com/standup-raven/standup-raven/server"]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["browser"]
plugins = ["react"]
style_guide = "airbnb"
