# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0

executors:
  ubuntu:
    docker:
      - image: cimg/base:stable
    parameters:
      resource_class:
        default: large
        type: string
    working_directory: ~/standup-raven
    resource_class: <<parameters.resource_class>>

jobs:
  plugin-ci/lint:
    steps:
      - run:
          name: "Check style"
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.2
            make check-style

  plugin-ci/test:
    steps:
      - run:
          name: "Run tests"
          command: |
            make test

  plugin-ci/build:
    steps:
      - run:
          name: "Build and bundle the plugin"
          command: |
            make dist
      - persist_to_workspace:
          paths: ~/standup-raven/dist

  deploy-release-github:
    docker:
      - image: cibuilds/github:latest
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/standup-raven/dist
      - run:
          name: "Publish Release on Github"
          command: |
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -b "$(< ./dist/release-notes.md)" -c "${CIRCLE_SHA1}" -n "${CIRCLE_TAG}" -delete "${CIRCLE_TAG}" dist
workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/test:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
      - deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: "standup-raven"
          requires:
            - plugin-ci/lint
            - plugin-ci/test
            - plugin-ci/build
