name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go v1.18.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Set up Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v3

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and bundle the plugin
        id: build
        run: |
          make dist
          echo ::set-output name=BUNDLE_NAME::$(cd dist; ls *.tar.gz)
        env:
          TERM: dumb

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            dist/mattermost-plugin-standup-raven-${{ github.ref_name }}-darwin-amd64.tar.gz
            dist/mattermost-plugin-standup-raven-${{ github.ref_name }}-linux-amd64.tar.gz
            dist/mattermost-plugin-standup-raven-${{ github.ref_name }}-windows-amd64.tar.gz
